INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, porte) VALUES ('Janjão', 1, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-20T10:30:00Z', 'Sujo/Castrado', 'Maria Laura', 'Médio');
INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, porte) VALUES ('Esmeralda', 1, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-21T10:30:00Z', 'Suja/PataMachucada', 'Débora', 'Pequena');
INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, data_adocao, condicao_chegada, nome_recebedor, porte) VALUES ('Marikita', 5, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-21T10:30:00Z', TIMESTAMP WITH TIME ZONE '2023-01-21T10:30:00Z','Pulgas', 'Maria Laura', 'Pequena');
INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, porte) VALUES ('Snoopy', 2, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-22T10:30:00Z', 'Pele Machucada', 'Maria Laura', 'Pequeno');
INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, porte) VALUES ('Américo', 10, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-22T10:30:00Z', 'Cego', 'Débora', 'Grande');
INSERT INTO cachorro (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, porte) VALUES ('Benjamin', 2, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-22T10:30:00Z', 'Sujo/Machucado', 'Maria Laura', 'Pequeno');

INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Colin', 1, 'SRD', TIMESTAMP WITH TIME ZONE '2022-09-20T10:30:00Z', 'Sujo', 'Maria Laura', 'Azul');
INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Bonfá', 1, 'SRD', TIMESTAMP WITH TIME ZONE '2022-09-21T10:30:00Z', 'Pata Machucada', 'Débora', 'Cinza');
INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, data_adocao, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Odete', 5, 'SRD', TIMESTAMP WITH TIME ZONE '2022-08-21T10:30:00Z', TIMESTAMP WITH TIME ZONE '2023-02-11T10:30:00Z','Pulgas', 'Maria Laura', 'Marrom');
INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Amarula', 2, 'SRD', TIMESTAMP WITH TIME ZONE '2022-09-22T10:30:00Z', 'Pele Machucada', 'Maria Laura', 'Preto');
INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Flash', 3, 'SRD', TIMESTAMP WITH TIME ZONE '2022-09-22T10:30:00Z', 'Cego', 'Débora', 'Azul');
INSERT INTO gato (nome_provisorio, idade_estimada, raca, data_entrada, condicao_chegada, nome_recebedor, cor_olho) VALUES ('Maribel', 3, 'SRD', TIMESTAMP WITH TIME ZONE '2022-09-22T10:30:00Z', 'Fraca', 'Maria Laura', 'Azul');